param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("Official", "ApiManaged")]
    [string]$Mode
)

$ErrorActionPreference = "Stop"

# ── Load config generated by setup.ps1 ───────────────────────────────────────
$ConfigFile = Join-Path $PSScriptRoot "..\config.ps1"
if (-not (Test-Path -LiteralPath $ConfigFile)) {
    Write-Error "config.ps1 not found. Run setup.bat first.`n  Expected: $ConfigFile"
    exit 1
}
. $ConfigFile

$CodexHome          = $Config.CodexHome
$CcSwitchDb         = $Config.CcSwitchDb
$CcSwitchSettings   = $Config.CcSwitchSettings
$NodeExe            = $Config.NodeExe

$SwitcherRoot       = Split-Path $PSScriptRoot -Parent
$BackupRoot         = Join-Path $SwitcherRoot "backups"
$OfficialState      = Join-Path $SwitcherRoot "state\official"
$ReadProviderScript = Join-Path $PSScriptRoot "read-provider.js"
$FixScript          = Join-Path $PSScriptRoot "fix-ccswitch-providers.js"

$ConfigPath         = Join-Path $CodexHome "config.toml"
$AuthPath           = Join-Path $CodexHome "auth.json"
$Utf8NoBom          = [System.Text.UTF8Encoding]::new($false)

# ── Utilities ─────────────────────────────────────────────────────────────────

function New-DirectoryIfMissing([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path)) {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
    }
}

function Get-Stamp { Get-Date -Format "yyyyMMdd-HHmmss" }

function Backup-FileIfExists([string]$Path, [string]$Label) {
    if (-not (Test-Path -LiteralPath $Path)) { return }
    New-DirectoryIfMissing $BackupRoot
    $name = Split-Path -Leaf $Path
    $dst  = Join-Path $BackupRoot "$(Get-Stamp)-$Label-$name"
    Copy-Item -LiteralPath $Path -Destination $dst -Force
    Write-Host "Backup: $dst"
}

function Stop-CodexProcesses {
    $names = @("Codex.exe","codex.exe","codex-plus-plus.exe","codex-plus-plus-manager.exe","cc-switch.exe")
    Write-Host "Stopping Codex / Codex++ / CC Switch processes..."
    Get-CimInstance Win32_Process |
        Where-Object { $names -contains $_.Name } |
        ForEach-Object {
            try {
                Write-Host ("  stopping {0} pid={1}" -f $_.Name, $_.ProcessId)
                Stop-Process -Id $_.ProcessId -Force -ErrorAction Stop
            } catch {
                Write-Host ("  warning: {0} pid={1}: {2}" -f $_.Name, $_.ProcessId, $_.Exception.Message)
            }
        }
    Start-Sleep -Seconds 2
}

function Get-AuthKind([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path)) { return "missing" }
    try {
        $j = Get-Content -Raw -LiteralPath $Path | ConvertFrom-Json
        if ($j.PSObject.Properties.Name -contains "OPENAI_API_KEY") { return "api" }
        return "chatgpt-or-other"
    } catch { return "unreadable" }
}

# ── TOML helpers ──────────────────────────────────────────────────────────────

function Get-TopLevelString([string]$Text, [string]$Key) {
    $m = [regex]::Match($Text, "(?m)^\s*$([regex]::Escape($Key))\s*=\s*`"([^`"]*)`"\s*$")
    if ($m.Success) { return $m.Groups[1].Value }
    return $null
}

function Remove-TopLevelKey([string]$Text, [string]$Key) {
    [regex]::Replace($Text, "(?m)^\s*$([regex]::Escape($Key))\s*=.*\r?\n?", "")
}

function Set-TopLevelString([string]$Text, [string]$Key, [string]$Value) {
    $line       = "$Key = `"$Value`""
    $escaped    = [regex]::Escape($Key)
    $firstTable = [regex]::Match($Text, "(?m)^\[.+\]\s*$")
    $topEnd     = if ($firstTable.Success) { $firstTable.Index } else { $Text.Length }
    $top        = $Text.Substring(0, $topEnd)
    $rest       = $Text.Substring($topEnd)
    if ($top -match "(?m)^\s*$escaped\s*=") {
        $top = [regex]::Replace($top, "(?m)^\s*$escaped\s*=.*$", $line, 1)
    } else {
        $top = $top.TrimEnd() + "`r`n$line`r`n"
    }
    $top + $rest
}

function Remove-TablesByPrefix([string]$Text, [string[]]$Prefixes) {
    $lines = $Text -split "\r?\n"
    $out   = [System.Collections.Generic.List[string]]::new()
    $skip  = $false
    foreach ($line in $lines) {
        if ($line -match '^\s*\[([^\]]+)\]\s*$') {
            $table = $Matches[1]; $skip = $false
            foreach ($p in $Prefixes) {
                if ($table -eq $p -or $table.StartsWith("$p.")) { $skip = $true; break }
            }
        }
        if (-not $skip) { $out.Add($line) }
    }
    ($out -join "`r`n").TrimEnd() + "`r`n"
}

function Ensure-TableString([string]$Text, [string]$Table, [string]$Key, [string]$Value) {
    $lines  = $Text.TrimEnd() -split "\r?\n"
    $header = "[$Table]"
    $start  = -1
    for ($i = 0; $i -lt $lines.Length; $i++) {
        if ($lines[$i].Trim() -eq $header) { $start = $i; break }
    }
    $newLine = "$Key = `"$Value`""
    if ($start -lt 0) {
        return ($lines -join "`r`n") + "`r`n`r`n$header`r`n$newLine`r`n"
    }
    $end = $lines.Length
    for ($i = $start + 1; $i -lt $lines.Length; $i++) {
        if ($lines[$i] -match '^\s*\[.+\]\s*$') { $end = $i; break }
    }
    for ($i = $start + 1; $i -lt $end; $i++) {
        if ($lines[$i] -match "^\s*$([regex]::Escape($Key))\s*=") {
            $lines[$i] = $newLine
            return ($lines -join "`r`n") + "`r`n"
        }
    }
    $before = @($lines[0..$start])
    $after  = if ($start + 1 -le $lines.Length - 1) { @($lines[($start+1)..($lines.Length-1)]) } else { @() }
    (@($before + $newLine + $after) -join "`r`n") + "`r`n"
}

# ── CC Switch reader ───────────────────────────────────────────────────────────

function Read-CcSwitchCurrentProvider {
    if (-not (Test-Path -LiteralPath $CcSwitchSettings)) {
        throw "CC Switch settings not found: $CcSwitchSettings"
    }
    if (-not (Test-Path -LiteralPath $CcSwitchDb)) {
        throw "CC Switch database not found: $CcSwitchDb"
    }
    if (-not (Test-Path -LiteralPath $NodeExe)) {
        throw "Node.js not found: $NodeExe"
    }
    if (-not (Test-Path -LiteralPath $ReadProviderScript)) {
        throw "read-provider.js not found: $ReadProviderScript"
    }

    # Pass settings.json path to Node.js so it reads currentProviderCodex as UTF-8.
    # Avoids PowerShell 5.1 encoding issues with non-ASCII provider IDs.
    $json = & $NodeExe $ReadProviderScript $CcSwitchDb $CcSwitchSettings 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to read provider from CC Switch: $json"
    }

    try {
        $parsed = $json | ConvertFrom-Json
        return [pscustomobject]@{ Id = $parsed.id; Data = $parsed }
    } catch {
        throw "Failed to parse provider JSON: $_"
    }
}

# ── Mode: API Managed ─────────────────────────────────────────────────────────

function Switch-ToApiManaged {
    Stop-CodexProcesses
    New-DirectoryIfMissing $BackupRoot
    New-DirectoryIfMissing $OfficialState
    Backup-FileIfExists -Path $ConfigPath                              -Label "pre-api"
    Backup-FileIfExists -Path $AuthPath                               -Label "pre-api"
    Backup-FileIfExists -Path (Join-Path $CodexHome "state_5.sqlite") -Label "pre-api-sessions"

    $authKind = Get-AuthKind -Path $AuthPath
    if ($authKind -eq "chatgpt-or-other") {
        Copy-Item -LiteralPath $AuthPath -Destination (Join-Path $OfficialState "auth.json") -Force
        Write-Host "Saved official auth tokens for future restore."
    }

    Write-Host ""
    Write-Host "Reading current provider from CC Switch..."
    $provider = Read-CcSwitchCurrentProvider
    Write-Host "Provider ID: $($provider.Id)"

    if ($provider.Data.auth) {
        $authJson = $provider.Data.auth | ConvertTo-Json -Depth 5 -Compress
        [System.IO.File]::WriteAllText($AuthPath, $authJson, $Utf8NoBom)
        Write-Host "Auth applied from CC Switch."
    } else {
        # No auth in provider — remove stale auth.json to prevent old key being used with new provider.
        Write-Host "Warning: no auth field in CC Switch provider. Clearing auth.json to prevent credential mismatch."
        if (Test-Path -LiteralPath $AuthPath) {
            Remove-Item -LiteralPath $AuthPath -Force
            Write-Host "auth.json removed. Codex will prompt for credentials on next launch."
        }
    }

    if (-not (Test-Path -LiteralPath $ConfigPath)) {
        throw "config.toml not found: $ConfigPath"
    }
    $text = [System.IO.File]::ReadAllText($ConfigPath, $Utf8NoBom)

    foreach ($key in @("openai_base_url", "chatgpt_base_url")) {
        $text = Remove-TopLevelKey -Text $text -Key $key
    }

    if ($provider.Data.config) {
        $pConfig   = $provider.Data.config
        $pProvider = Get-TopLevelString -Text $pConfig -Key "model_provider"
        if ($pProvider) {
            $text = Remove-TopLevelKey  -Text $text -Key "model_provider"
            $text = Set-TopLevelString  -Text $text -Key "model_provider" -Value $pProvider
            Write-Host "model_provider = $pProvider"
        }

        $text    = Remove-TablesByPrefix -Text $text -Prefixes @("model_providers")
        $pLines  = $pConfig -split "\r?\n"
        $section = [System.Collections.Generic.List[string]]::new()
        $inSect  = $false
        foreach ($line in $pLines) {
            if ($line -match '^\s*\[model_providers')   { $inSect = $true }
            elseif ($inSect -and $line -match '^\s*\[') { $inSect = $false }
            if ($inSect) { $section.Add($line) }
        }
        if ($section.Count -gt 0) {
            $text = $text.TrimEnd() + "`r`n`r`n" + ($section -join "`r`n") + "`r`n"
        }
    } else {
        Write-Host "Warning: no config in CC Switch provider; provider section left as-is."
    }

    # Sanitize model_reasoning_effort — "xhigh" (added by Codex++ UI) crashes the binary
    $currentEffort = Get-TopLevelString -Text $text -Key "model_reasoning_effort"
    if ($currentEffort -and $currentEffort -notin @("low","medium","high")) {
        Write-Host "Warning: model_reasoning_effort '$currentEffort' is not valid — resetting to 'high'"
        $text = Set-TopLevelString -Text $text -Key "model_reasoning_effort" -Value "high"
    }

    $text = Set-TopLevelString -Text $text -Key "sandbox_mode"        -Value "danger-full-access"
    $text = Set-TopLevelString -Text $text -Key "approval_policy"     -Value "never"
    $text = Set-TopLevelString -Text $text -Key "forced_login_method" -Value "api"
    $text = Ensure-TableString  -Text $text -Table "history" -Key "persistence" -Value "save-all"
    [System.IO.File]::WriteAllText($ConfigPath, $text.TrimEnd() + "`r`n", $Utf8NoBom)

    if ((Test-Path -LiteralPath $NodeExe) -and (Test-Path -LiteralPath $FixScript)) {
        Write-Host ""
        Write-Host "Patching CC Switch provider configs..."
        & $NodeExe $FixScript $CcSwitchDb 2>&1 |
            Where-Object { $_ -match 'UPDATED|Done' } |
            ForEach-Object { Write-Host "  $_" }
    }

    Write-Host ""
    Write-Host "API mode ready. CC Switch manages the provider."
    Write-Host "Switch providers in CC Switch at any time — no need to re-run this script."
}

# ── Mode: Official ────────────────────────────────────────────────────────────

function Switch-ToOfficial {
    Stop-CodexProcesses
    New-DirectoryIfMissing $BackupRoot
    New-DirectoryIfMissing $OfficialState
    Backup-FileIfExists -Path $ConfigPath -Label "pre-official"
    Backup-FileIfExists -Path $AuthPath   -Label "pre-official"

    $officialConfigPath = Join-Path $OfficialState "config.toml"
    if (Test-Path -LiteralPath $officialConfigPath) {
        Copy-Item -LiteralPath $officialConfigPath -Destination $ConfigPath -Force
        Write-Host "Restored saved official config."
    } else {
        if (-not (Test-Path -LiteralPath $ConfigPath)) {
            throw "config.toml not found: $ConfigPath"
        }
        $text = [System.IO.File]::ReadAllText($ConfigPath, $Utf8NoBom)
        foreach ($key in @("model_provider","openai_base_url","chatgpt_base_url","service_tier","disable_response_storage")) {
            $text = Remove-TopLevelKey -Text $text -Key $key
        }
        $text = Remove-TablesByPrefix -Text $text -Prefixes @("model_providers")
        $text = Set-TopLevelString -Text $text -Key "model_provider"         -Value "openai"
        $text = Set-TopLevelString -Text $text -Key "model"                  -Value "gpt-5.5"
        $text = Set-TopLevelString -Text $text -Key "model_reasoning_effort" -Value "high"
        $text = Set-TopLevelString -Text $text -Key "forced_login_method"    -Value "chatgpt"
        $text = Ensure-TableString  -Text $text -Table "history" -Key "persistence" -Value "save-all"
        [System.IO.File]::WriteAllText($ConfigPath, $text.TrimEnd() + "`r`n", $Utf8NoBom)
        Copy-Item -LiteralPath $ConfigPath -Destination $officialConfigPath -Force
        Write-Host "Wrote and saved new official config."
    }

    $officialAuthPath = Join-Path $OfficialState "auth.json"
    if (Test-Path -LiteralPath $officialAuthPath) {
        Copy-Item -LiteralPath $officialAuthPath -Destination $AuthPath -Force
        Write-Host "Restored saved official auth tokens."
    } elseif (Test-Path -LiteralPath $AuthPath) {
        Remove-Item -LiteralPath $AuthPath -Force
        Write-Host "Removed API key auth so Codex prompts for ChatGPT login."
    }

    Write-Host ""
    Write-Host "Official mode ready."
    Write-Host "Start Codex and sign in with your ChatGPT account."
}

# ── Entry point ────────────────────────────────────────────────────────────────

New-DirectoryIfMissing $BackupRoot
New-DirectoryIfMissing $OfficialState

if ($Mode -eq "Official") {
    Switch-ToOfficial
} else {
    Switch-ToApiManaged
}
